name: Build Linux Installers

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20 (npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org/

      # Rewrite any git+ssh deps to HTTPS so no SSH keys are needed on CI
      - name: Rewrite git+ssh deps to HTTPS
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
          git config --global url."https://".insteadOf git://

      - name: npm config (registry & retries)
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retries 5
          npm config set fetch-retry-maxtimeout 600000
          npm config set audit false
          npm config set fund false

      # Ensure we have a 512x512 PNG for Linux icons
      - name: Ensure 512x512 PNG app icon
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick file
          if [ -f assets/icon.png ]; then
            # If icon.png exists but is too small, upscale to 512x512
            WIDTH=$(identify -format "%w" assets/icon.png || echo 0)
            if [ "$WIDTH" -lt 256 ]; then
              convert assets/icon.png -resize 512x512 assets/icon.png
            fi
          elif [ -f assets/icon.ico ]; then
            # Make a 512x512 PNG from the first frame of the ICO
            convert assets/icon.ico[0] -resize 512x512 assets/icon.png
          else
            echo "::error ::No icon found at assets/icon.png or assets/icon.ico"
            exit 1
          fi

      - name: Install deps (use lockfile if present; otherwise fallback)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund --registry=https://registry.npmjs.org/ || npm i --no-audit --no-fund --registry=https://registry.npmjs.org/
          else
            npm i --no-audit --no-fund --registry=https://registry.npmjs.org/
          fi

      - name: Build Linux (AppImage + deb)
        run: npx electron-builder --linux AppImage deb -p never
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts-x64
          path: dist/*
          if-no-files-found: error
