name: Build Linux Installers

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20 (npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          # Force the public npm registry (avoids private-registry 403s)
          registry-url: https://registry.npmjs.org/

      # If any dependency references GitHub via SSH, rewrite to HTTPS so no SSH keys are needed
      - name: Rewrite git+ssh deps to HTTPS
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
          git config --global url."https://".insteadOf git://

      # Make npm robust + point at npmjs explicitly
      - name: npm config (registry & retries)
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retries 5
          npm config set fetch-retry-maxtimeout 600000
          npm config set prefer-online true
          npm config set always-auth false
          npm config set fund false
          npm config set audit false

      - name: Install deps (use lockfile if present; otherwise fallback)
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm i --no-audit --no-fund
          else
            npm i --no-audit --no-fund
          fi

      - name: Build Linux (AppImage + deb)
        run: npx electron-builder --linux AppImage deb -p never
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts-x64
          path: dist/*
          if-no-files-found: error
