name: Build Linux Installers

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ x64 ]  # add arm64 if you want ARM builds too
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Linux (AppImage + deb)
        run: npx electron-builder --linux AppImage deb -p never
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts-${{ matrix.arch }}
          path: dist/*
          if-no-files-found: error
